apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: rails
  name: rails-ext-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: rails
  type: NodePort
status:
  loadBalancer: {}
