# Exercise 4: Create a PersistentVolumeClaim

# Create a PersistentVolumeClaim YAML definition file with a request that matches the PersistentVolume created in Exercise 3.
# Deploy the PersistentVolumeClaim to your Kubernetes cluster.
# Verify that the PersistentVolumeClaim is created and bound to the PersistentVolume from Exercise 3.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-persistentvolumeclaim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: custom-storageclass
  resources:
    requests:
      storage: 500Mi
