apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: admin
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - serviceaccounts
  - configmaps
  - secrets
  verbs:
  - create
  - get
  - update
  - delete
