apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  volumes:
    - name: mysql-volume
      secrets:
        secretName: mysql-secret
  containers:
    - name: mysql
      image: mysql
      volumeMounts:
        mountPath: /var/lib
      env:
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "123456789"
        - name: MYSQL_DATABASE
          value: "mysql-db"
