apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql-service
  name: mysql-service
spec:
  ports:
  - name: 3306-3306
    nodePort: 30060
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-service
  type: NodePort
status:
  loadBalancer: {}
